myshop/mycart/urls.py
from django.urls import path
from . import views

app_name = 'myshop'

urlpatterns = [
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',
         views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),
]

myshop/myshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('mycart.urls', namespace='mycart')),
    path('tinymce/', include('tinymce.urls')),
]
if settings.DEBUG:
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.home, name='homepage'),
    path('register/', views.register, name='register'),
    path("login", views.login_request, name='login'),
    path("logout", views.logout_request, name="logout"),
    path('<category_slug>/', views.product_list, name= "all_list"),
    path('<category_slug>/<type_slug>', views.product_list, name='product_list_by_category'),
    path('<id>/<slug>/', views.product_detail, name='product_detail'),
    
]

myshop/shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:all_list', args=[self.slug])


class Type(models.Model):
    name=models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    category = models.ForeignKey(Category, related_name='types',on_delete=models.PROTECT)

    class Meta:
        ordering = ('name',)
        verbose_name = 'type'
        verbose_name_plural = 'types'
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.category.slug,self.slug])


class Product(models.Model):
    product_type = models.ForeignKey(Type, related_name='products',on_delete=models.PROTECT)
    category = models.ForeignKey(Category, related_name='categories',on_delete=models.PROTECT)
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    image2 = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    image3 = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.FloatField()
    pair = models.BooleanField(default=False)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ('-created',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

myshop/shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib import messages

class SignUp(UserCreationForm):
    email = forms.EmailField(required=True, label='Email')

    class Meta:
        model = User
        fields = ("username","email", "password1","password2")

    def save(self, commit=True):
        user = super(SignUp, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        
        if password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def clean_username(self):
        email=self.cleaned_data.get("email")
        username=self.cleaned_data.get("username")
        if User.objects.filter(username=self.cleaned_data['username']).exists():
            self.error_messages['username_exists']="username already exists"
            raise forms.ValidationError(
            self.error_messages['username_exists'],
                code='username_exists',
            )
        return username

myshop/shop/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Category, Product,Type
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import logout, authenticate, login
from django.contrib import messages
from .forms import  SignUp
from django.http import HttpResponse
from django.contrib.auth.models import User
#from cart.forms import CartAddProductForm
def product_list(request, category_slug, type_slug=None):
    product_type=None
    category = get_object_or_404(Category, slug=category_slug)
    types = Type.objects.filter(category=category)
    if request.GET.get('price_filter')=='3':
        products = Product.objects.filter(available=True, category=category).order_by('-price')
    elif request.GET.get('price_filter')=='2':
        products = Product.objects.filter(available=True, category=category).order_by('price')
    else:
        products = Product.objects.filter(available=True,category=category)
    if type_slug:
        product_type = get_object_or_404(Type, slug=type_slug)
        products.filter(product_type=product_type)
    return render(request, 'category.html', {'category': category,
                                                      'types': types,
                                                      'products': products,
                                                      'product_type':product_type,
                                                      })
def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    #cart_product_form = CartAddProductForm()
    return render(request, 'detail.html', {'product': product,
                                                        #'cart_product_form': cart_product_form
                                                        })
def home(request):
    categories = Category.objects.all()
    return render(request, template_name='homepage.html',context= {'categories': categories} )

def register(request):
    if request.method == "POST":
        form = SignUp(data=request.POST)
        if form.is_valid():
            if User.objects.filter(email=form.cleaned_data['email']).exists():
                messages.error(request, f"Account associated with this email already exists, Login instead")
                return render(request = request,
                          template_name = "register.html",
                          context={"form":form})
            else:
                user = form.save()
                username = form.cleaned_data.get('username')
                login(request, user)
                messages.success(request, f"New account created: {username}")
                return redirect("/")

        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")

            return render(request = request,
                          template_name = "register.html",
                          context={"form":form})
   
    form = SignUp
    return render(request = request,
                template_name = "register.html",
                context={"form":form})

def logout_request(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("/")

def login_request(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f"You are now logged in as {username}")
                return redirect('/')
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request = request,
                    template_name = "login.html",
                    context={"form":form})

myshop/shop/templates/category.html
{% extends 'header.html' %}
{% load static %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
<!-- semi navbar-->
<div class="sticky-top">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class=" btn btn-warning navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
<ul class="navbar-nav mr-auto">
      <li class="nav-item">
    <div class="row">
    <div class="col-sm">
      <div class="fluid-container">
  <div class="dropdown">
              <button class="btn btn-warning btn-lg dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                 Filter
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="{{ category.get_absolute_url }}">All</a>
              {% for t in types %}
                  <a class="dropdown-item" href="{{ t.get_absolute_url }}">{{ t.name }}</a>
              {% endfor %}
              </div>
          </div>
</div>
</div>
<div class="col-sm">
      <div class="fluid-container">
  <form class="form-inline" method='get' {% if product_type %} action='/{{ category.slug }}/{{product_type.slug}}'{% else %} action='/{{category.slug}}'{% endif %}>
      <label class="my-1 mr-2" for="inlineFormCustomSelectPref"></label>
      <select class="custom-select my-1 mr-sm-2" id="inlineFormCustomSelectPref" name="price_filter">
    <option value="1">Relevance</option>
    <option value="2">Price Low To High</option>
    <option value="3">Price High To Low</option>
      </select>
    <button type="submit" class="btn btn-warning my-1">Submit</button>
      </form>
      </div>
      </div>
  </li>
  </ul>
  <ul class="navbar-nav ml-auto">
  <li class="nav-item">
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Search</button>
  </form>
  </li>
  </ul>
  </div>
  </nav>
  </div>
  <!-- dropdown 
    <div class="col-sm">
      <div class="fluid-container">
          <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                 Filter
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="{{ category.get_absolute_url }}">All</a>
              {% for t in types %}
                  <a class="dropdown-item" href="{{ t.get_absolute_url }}">{{ t.name }}</a>
              {% endfor %}
              </div>
          </div>
      </div>
    </div>
    <!-- sorting 
    <div class="col-sm">  
    <div class="fluid-container" >
      <form class="form-inline" method='get' {% if product_type %} action='/{{ category.slug }}/{{product_type.slug}}'{% else %} action='/{{category.slug}}'{% endif %}>
      <label class="my-1 mr-2" for="inlineFormCustomSelectPref"></label>
      <select class="custom-select my-1 mr-sm-2" id="inlineFormCustomSelectPref" name="price_filter">
    <option value="1">Relevance</option>
    <option value="2">Price Low To High</option>
    <option value="3">Price High To Low</option>
      </select>
    <button type="submit" class="btn btn-primary my-1">Submit</button>
      </form>
      </div>
      </div>
<!-- search 
    <div class="col-sm">
    <div class="fluid-container" >
      <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
    </div>
  </div>
</div>-->

<!-- MAIN -->

<div class="container">
        {% if product_type.slug == None %}
        <div id="main" style="margin-top:20px;">
        <h1>{% if product_type %}{{ product_type.name }}{% else %}Products{% endif %}</h1>
        <div class="row">
            {% for product in products %}
              <div class="col-sm-4">
                    <div class="card">
                    <a href="{{ product.get_absolute_url }}">
                            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" class="card-img-top" alt="...">
                        </a>
                        <div class="card-body">
                            <h5 class="card-title"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br></h5>
                            <p class="card-text">${{ product.price }}</p>
                            <a href="{{ product.get_absolute_url }}" class="btn btn-primary">Details</a>
                        </div>
                         <div class="card-body">
                            <a href="#" class="card-link">Wishlist</a>
                            <a href="#" class="card-link">Add to cart</a>
                        </div>
                        </div>
                        </div>
                    {% endfor %} 
                     </div>
        </div>  
        {% else %}
        <div id="main" style="margin-top:20px;">
        <h1>{% if product_type %}{{ product_type.name }}{% else %}Products{% endif %}</h1>
        <div class="row">
            {% for product in products %}
                {% if product.product_type.slug == product_type.slug %}
                    <div class="col-sm-4">
                    <div class="card">
                    <a href="{{ product.get_absolute_url }}">
                            <img src="{% if product.image1 %}{{ product.image1.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" class="card-img-top" alt="...">
                        </a>
                        <div class="card-body">
                            <h5 class="card-title"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br></h5>
                            <p class="card-text">${{ product.price }}</p>
                            <a href="{{ product.get_absolute_url }}" class="btn btn-primary">Details</a>
                        </div>
                         <div class="card-body">
                            <a href="#" class="card-link">Wishlist</a>
                            <a href="#" class="card-link">Add to cart</a>
                        </div>
                        </div>
                        </div>
                        {% endif %}
                    {% endfor %} 
                     </div>
        </div>  
        {% endif%}
</div>
  
  {% endblock %}
    

myshop/shop/templates/detail.html
{% extends 'header.html' %}
{% load static %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}

<div >
<nav class="navbar navbar-dark bg-dark" >
<ul class="navbar-nav ml-auto">
      <li class="nav-item">
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Search</button>
  </form>
  </li>
  </ul>
  </nav>
  </div>
<a href="{% url 'mycart:cart_add' product.id %}">Add To Cart</a>

<div class="container">
    <div class="row row-cols-1 row-cols-md-2 h-100 " style="margin-top: 2%">
    <div class="col mb-4">

<div class="card" >
  <div class="card-body bg-warning">
    <strong style="text-transform: capitalize;"><i>{{product.name}}</i> {{product.product_type}}</strong>
  </div>
</div>

    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% if product.image2 %}{{ product.image2.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% if product.image3 %}{{ product.image3.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>
<div class="col mb-4" >
<div class="card text-white bg-secondary mb-3">
  <div class="card-header" style="text-transform: capitalize;">{{ product.name }}</div>
  <div class="card-body">
    <h5 class="card-title" style="text-transform: capitalize;">${{ product.price }}</h5>
    <p class="card-text" style="text-transform: capitalize;">{{ product.description|linebreaks }}</p>
    {% if product.pair%}
    <p class="card-text" style="text-transform: capitalize;"><strong>Available in pair</strong></p>
    {% endif %}
    <p class="card-text"> Tags: <a href="{{ product.category.get_absolute_url }}"><i>{{ product.category }}</i></a>, <a href="{{ product.product_type.get_absolute_url }}"><i>{{ product.product_type }}</i></a></p>
  </div>
  </div>
<button type="button" class="btn btn-outline-warning btn-lg btn-block" data-toggle="modal" data-target="#exampleModal"><svg class="bi bi-cart-plus" width="2em" height="2em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M8.5 5a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1H8V5.5a.5.5 0 0 1 .5-.5z"/>
  <path fill-rule="evenodd" d="M8 7.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1H9v1.5a.5.5 0 0 1-1 0v-2z"/>
  <path fill-rule="evenodd" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
</svg></button>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Success!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Item added to cart.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <a href="#" ><button type="button" class="btn btn-primary">Go to Cart</button></a>
      </div>
    </div>
  </div>
</div>
        <br>
        <button type="button" class="btn btn-outline-danger btn-lg btn-block" data-toggle="modal" data-target="#exampleModal"><svg class="bi bi-heart" width="2em" height="2em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
</svg></button>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">SuccesS!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Item added to wishlist.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <a href="#" ><button type="button" class="btn btn-primary">See Wishlist</button></a>
      </div>
    </div>
  </div>
</div>
</div>
</div>
</div>

{% endblock %}

myshop/shop/templates/header.html
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!--bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script></head>
<!-- W3schools-->
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open Sans">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
</style>
<body>


  {% include 'includes/navbar.html' %}
  {% include 'includes/messaging.html' %}
    {% block content %}
    {% endblock %}
    {% include 'includes/footer.html' %}

</body>

myshop/shop/templates/homepage.html
{% extends 'header.html' %}
{% load static %}

{% block content %}
<div class="sticky-top">
<nav class="navbar navbar-dark bg-dark" >
<ul class="navbar-nav ml-auto">
      <li class="nav-item">
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Search</button>
  </form>
  </li>
  </ul>
  </nav>
  </div>
<div class="container">
<div class="row row-cols-1 row-cols-md-2 align-items-center">
{% for c in categories %}
<div class="col mb-4" style="margin-top: 10%;">
<div class="card bg-dark text-white h-100">
<a href="{{ c.get_absolute_url }}">
  <img src="{{ c.image.url }}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title" style="color: #FF7F24">Shop {{ c.name }} >></h5>
    <p class="card-text" >{{c.description}}</p>
  </div>
</a>
</div>
</div>

{% endfor %}
</div></div>
  {% endblock %}

myshop/shop/templates/login.html
{% extends 'header.html' %}
{% load bootstrap4 %}

{% block content %}

    <div class="container" style="padding:auto; margin:auto;">
        <form method="POST"style="margin-top:50px;">
        {% csrf_token %}
        {% bootstrap_form form %}
            <button class="btn btn btn-primary" type="submit">Login</button>
        </form>
        Don't have an account? <a href="/register" target="blank"><strong>register here</strong></a>!
    </div>
{% endblock %}

myshop/shop/templates/register.html
{% extends 'header.html' %}
{% load bootstrap4 %}

{% block content %}
    <div class="container" style="padding:auto; margin:auto;">
        <form method="POST" style="margin-top:50px;">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="btn btn btn-primary" type="submit">Register</button>
        </form>

    If you already have an account <a href="/login" target="blank"><strong>login</strong></a> instead.
</div>
{% endblock %}